# File names

# Clooney
clooney_train = "clooney_ext_otu_train.csv"
clooney_test = "clooney_ext_otu_test.csv"
clooney_train_label = "clooney_ext_otu_train_y.csv"
clooney_test_label = "clooney_ext_otu_test_y.csv"
clooney_ext_phylo = "clooney_ext_phylo.csv"

clooney_train_cnt = "clooney_ext_otu_train_cnt.csv"
clooney_test_cnt = "clooney_ext_otu_test_cnt.csv"
clooney_train_label_cnt = "clooney_ext_otu_train_y_cnt.csv"
clooney_test_label_cnt = "clooney_ext_otu_test_y_cnt.csv"
clooney_ext_phylo_cnt = "clooney_ext_phylo_cnt.csv"


#data/DeepMicro
c_abundance_IBD= "abundance_IBD.txt"
c_abundance_Colorectal= "abundance_Colorectal.txt"
c_abundance_Cirrhosis= "abundance_Cirrhosis.txt"
c_abundance_WT2D= "abundance_WT2D.txt"
c_abundance_T2D= "abundance_T2D.txt"
c_abundance_Obesity= "abundance_Obesity.txt"

#data/gmhi
c_4347_final_relative_abundances= "4347_final_relative_abundances.txt"
c_Final_metadata_4347= "Final_metadata_4347.csv"
c_validation_abundance= "validation_abundance.csv"
c_validation_metadata1= "validation_metadata1.csv"

#data/giliberti/meta
c_CastroNallarE_2015= "Castro-NallarE_2015.txt"
c_ChngKR_2016= "ChngKR_2016.txt"
c_FengQ_2015= "FengQ_2015.txt"
c_GhensiP_2019= "GhensiP_2019.txt"
c_GhensiP_2019_m= "GhensiP_2019_m.txt"
c_GuptaA_2019= "GuptaA_2019.txt"
c_HMP_2012= "HMP_2012.txt"
c_HanniganGD_2017= "HanniganGD_2017.txt"
c_HeitzBuschartA_2016= "Heitz-BuschartA_2016.txt"
c_IjazUZ_2017= "IjazUZ_2017.txt"
c_JieZ_2017= "JieZ_2017.txt"
c_KarlssonFH_2013= "KarlssonFH_2013.txt"
c_KosticAD_2015= "KosticAD_2015.txt"
c_LiJ_2017= "LiJ_2017.txt"
c_NielsenHB_2014= "NielsenHB_2014.txt"
c_QinJ_2012= "QinJ_2012.txt"
c_QinN_2014= "QinN_2014.txt"
c_RaymondF_2016= "RaymondF_2016.txt"
c_ThomasAM_2018a= "ThomasAM_2018a.txt"
c_ThomasAM_2018b= "ThomasAM_2018b.txt"
c_VogtmannE_2016= "VogtmannE_2016.txt"
c_WirbelJ_2018= "WirbelJ_2018.txt"
c_YachidaS_2019= "YachidaS_2019.txt"
c_YeZ_2018= "YeZ_2018.txt"
c_YuJ_2015= "YuJ_2015.txt"
c_ZellerG_2014= "ZellerG_2014.txt"

#data/giliberti/16s
c_asd_son= "asd_son.csv"
c_autism_kb= "autism_kb.csv"
c_cdi_schubert= "cdi_schubert.csv"
c_cdi_vincent_v3v5= "cdi_vincent_v3v5.csv"
c_cdi_youngster= "cdi_youngster.csv"
c_crc_baxter= "crc_baxter.csv"
c_crc_xiang= "crc_xiang.csv"
c_crc_zeller= "crc_zeller.csv"
c_crc_zhao= "crc_zhao.csv"
c_edd_singh= "edd_singh.csv"
c_hiv_dinh= "hiv_dinh.csv"
c_hiv_lozupone= "hiv_lozupone.csv"
c_hiv_noguerajulian= "hiv_noguerajulian.csv"
c_ibd_alm= "ibd_alm.csv"
c_ibd_engstrand_maxee= "ibd_engstrand_maxee.csv"
c_ibd_gevers_2014= "ibd_gevers_2014.csv"
c_ibd_huttenhower= "ibd_huttenhower.csv"
c_mhe_zhang= "mhe_zhang.csv"
c_nash_baker= "nash_baker.csv"
c_nash_chan= "nash_chan.csv"
c_nash_ob_baker= "nash_ob_baker.csv"
c_non_cdi_schubert= "non_cdi_schubert.csv"
c_ob_baker= "ob_baker.csv"
c_ob_goodrich= "ob_goodrich.csv"
c_ob_gordon_2008_v2= "ob_gordon_2008_v2.csv"
c_ob_ross= "ob_ross.csv"
c_ob_zupancic= "ob_zupancic.csv"
c_par_scheperjans= "par_scheperjans.csv"
c_ra_littman= "ra_littman.csv"
c_t1d_alkanani= "t1d_alkanani.csv"
c_t1d_mejialeon= "t1d_mejialeon.csv"
#data/MBGAN
c_raw_data= "raw_data.pkl"
